site_name: pyjokes
theme: mkdocs
site_url: http://pyjok.es/
repo_url: https://github.com/pyjokes/pyjokes
site_description: One-line programmer jokes (jokes-as-a-service)
site_author: Pyjokes Society
site_dir: pythonhosted
google_analytics: ['UA-65996819-1', 'pyjok.es']
pages:
- 'Home': 'index.md'
- 'Install': 'install.md'
- 'API Reference': 'api.md'
- 'Pyjokes Society': 'society.md'
